# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/power-baseball-girl"

# 网页的标题
title: "Power Baseball Girl"
username: Timbo
# 网站副标题
description: "棒！少女"

aboutme: "强棒少女-的莫曲里"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
